version: '3'
services:
  broker:
    image: broker
    build: 
      context: .
      dockerfile: ./broker/Dockerfile
    environment:
      - ZMQ_MANAGER_ADDRESS=tcp://*:5559
      - ZMQ_PUB_ADDRESS=tcp://*:5560
      - ZMQ_ROUTER_ADDRESS=tcp://*:5561

  manager:
    image: manager
    depends_on:
      - broker
      - worker1
      - worker2
    build:
      context: .
      dockerfile: ./manager/Dockerfile
    environment:
      - ZMQ_BROKER_ADDRESS=tcp://broker:5559
      - GRPC_ADDRESS=0.0.0.0:5300

  client:
    image: client
    depends_on:
      - manager
    build:
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      - GRPC_ADDRESS=dns:///manager:5300

  worker1:
    image: worker
    depends_on:
      - broker
    build: 
      context: .
      dockerfile: ./worker/Dockerfile
    environment:
      - ZMQ_SUB_ADDRESS=tcp://broker:5560
      - ZMQ_DEALER_ADDRESS=tcp://broker:5561
      - WORKER_IDENTITY=w1
      - CORE_COUNT=2

  worker2:
    image: worker
    depends_on:
      - broker
    build: 
      context: .
      dockerfile: ./worker/Dockerfile
    environment:
      - ZMQ_SUB_ADDRESS=tcp://broker:5560
      - ZMQ_DEALER_ADDRESS=tcp://broker:5561
      - WORKER_IDENTITY=w2
      - CORE_COUNT=2

