version: '3'
services:
  broker:
    image: broker
    build: 
      context: .
      dockerfile: ./broker/Dockerfile
    environment:
      - ZMQ_MANAGER_ADDRESS=tcp://*:5559
      - ZMQ_PUB_ADDRESS=tcp://*:5560
      - ZMQ_ROUTER_ADDRESS=tcp://*:5561

  database:
    image: db_server
    build:
      context: .
      dockerfile: ./database/Dockerfile
    environment:
      - DB_PATH=database.db
      - DB_ADDRESS=0.0.0.0:5301

  manager:
    image: manager
    depends_on:
      - broker
      - database
      - worker1
      - worker2
      - worker3
      - worker4
    build:
      context: .
      dockerfile: ./manager/Dockerfile
    environment:
      - ZMQ_BROKER_ADDRESS=tcp://broker:5559
      - GRPC_ADDRESS=0.0.0.0:5300
      - DB_ADDRESS=dns:///database:5301

  client:
    image: client
    depends_on:
      - manager
    build:
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      - GRPC_ADDRESS=dns:///manager:5300

  worker1:
    image: worker
    depends_on:
      - broker
    build: 
      context: .
      dockerfile: ./worker/Dockerfile
    environment:
      - ZMQ_SUB_ADDRESS=tcp://broker:5560
      - ZMQ_DEALER_ADDRESS=tcp://broker:5561
      - DB_ADDRESS=dns:///database:5301
      - WORKER_IDENTITY=w1
      - CORE_COUNT=2

  worker2:
    image: worker
    depends_on:
      - broker
    build: 
      context: .
      dockerfile: ./worker/Dockerfile
    environment:
      - ZMQ_SUB_ADDRESS=tcp://broker:5560
      - ZMQ_DEALER_ADDRESS=tcp://broker:5561
      - DB_ADDRESS=dns:///database:5301
      - WORKER_IDENTITY=w2
      - CORE_COUNT=2

  worker3:
    image: worker
    depends_on:
      - broker
    build: 
      context: .
      dockerfile: ./worker/Dockerfile
    environment:
      - ZMQ_SUB_ADDRESS=tcp://broker:5560
      - ZMQ_DEALER_ADDRESS=tcp://broker:5561
      - DB_ADDRESS=dns:///database:5301
      - WORKER_IDENTITY=w3
      - CORE_COUNT=2

  worker4:
    image: worker
    depends_on:
      - broker
    build: 
      context: .
      dockerfile: ./worker/Dockerfile
    environment:
      - ZMQ_SUB_ADDRESS=tcp://broker:5560
      - ZMQ_DEALER_ADDRESS=tcp://broker:5561
      - DB_ADDRESS=dns:///database:5301
      - WORKER_IDENTITY=w4
      - CORE_COUNT=2
